version: '3.8'

services:
  db:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: examplepassword
      MYSQL_DATABASE: railway
      MYSQL_USER: a
      MYSQL_PASSWORD: a
      TZ: Asia/Tokyo
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql/sql:/docker-entrypoint-initdb.d

volumes:
  db_data: